### ISSUE TITLE
I got reference error.

### ISSUE THREAD

**Issue by Jongkeun21** [masenf/experiment-countdown-component#1]
Hello! I am studying pynecone nowadays. 

I want to add 'signature canvas' to my app. I thought I need to know how to use _get_hooks(). 

So I tried to follow your code. 
But I got reference error. I copied your code and pasted to my app.
![image](https://user-images.githubusercontent.com/49437473/237011488-366fe92c-e634-43a4-a227-66ed1581c21b.png)

Just adding code like below at js file, it works.
```
const countdown_reference = useRef(null)
```

What should I do?

**Comment by masenf** [comment]
Might have changed in recent versions, looks like some of the vars have changed how they are implemented.

I don't know the problem off the top of my head. But when I get a chance to retest on the latest release that came out yesterday, I'll update the example.

**Comment by masenf** [comment]
@Jongkeun21 I just pushed an update https://github.com/masenf/experiment-countdown-component/commit/ee56b0acdbfb98dd1bb5041d240788de4292cb7a

Please see if this addresses the issue your were seeing.

**Comment by Jongkeun21** [comment]
@masenf I forgot this issue, and now I have seen it. 
After changing my code, it works!! Thank you for your help.
